service: student-management-rest-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:ap-southeast-1:*:*

custom:
  aws_bucket_name: "cloud-comuting-student-management"
  aws_bucket_region: "ap-southeast-1"
  aws_access_key: "AKIA4HFALN6GRU4DQTWG"
  aws_secret_key: "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"
  
resources:
  Resources:
    StudentsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'students'
    ManagersTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'managers'
    FacultysTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'facultys'
    SchoolYearsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'schoolYears'
    FormsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'forms'

functions:
  registerStudent:
    handler: src/handler/auth/register.register
    events:
      - http:
          path: auth/register
          method: post
          cors: true
  login:
    handler: src/handler/auth/login.login
    events:
      - http:
          path: auth/login
          method: post
          cors: true
  changePassword:
    handler: src/handler/auth/changePassword.changePassword
    events:
      - http:
          path: auth/changePassword
          method: post
          cors: true

  createStudent:
    handler: src/handler/students/createStudent.createStudent
    events:
      - http:
          path: students
          method: post
          cors: true
    timeout: 20
  listStudent:
    handler: src/handler/students/listStudent.listStudent
    events:
      - http:
          path: students
          method: get
          cors: true
    timeout: 20
  getStudent:
    handler: src/handler/students/getStudent.getStudent
    events:
      - http:
          path: students/{id}
          method: get
          cors: true
    timeout: 20
  updateStudent:
    handler: src/handler/students/updateStudent.updateStudent
    events:
      - http:
          path: students/{id}
          method: put
          cors: true
    timeout: 20
  deleteStudent:
    handler: src/handler/students/deleteStudent.deleteStudent
    events:
      - http:
          path: students/{id}
          method: delete
          cors: true
    timeout: 20

  createManager:
    handler: src/handler/managers/createManager.createManager
    events:
      - http:
          path: managers
          method: post
          cors: true
    timeout: 20
  listManager:
    handler: src/handler/managers/listManager.listManager
    events:
      - http:
          path: managers
          method: get
          cors: true
    timeout: 20
  getManager:
    handler: src/handler/managers/getManager.getManager
    events:
      - http:
          path: managers/{id}
          method: get
          cors: true
    timeout: 20
  updateManager:
    handler: src/handler/managers/updateManager.updateManager
    events:
      - http:
          path: managers/{id}
          method: put
          cors: true
    timeout: 20
  deleteManager:
    handler: src/handler/managers/deleteManager.deleteManager
    events:
      - http:
          path: managers/{id}
          method: delete
          cors: true
    timeout: 20

  createFaculty:
    handler: src/handler/facultys/createFaculty.createFaculty
    events:
      - http:
          path: facultys
          method: post
          cors: true
    timeout: 20
  listFaculty:
    handler: src/handler/facultys/listFaculty.listFaculty
    events:
      - http:
          path: facultys
          method: get
          cors: true
    timeout: 20
  getFaculty:
    handler: src/handler/facultys/getFaculty.getFaculty
    events:
      - http:
          path: facultys/{id}
          method: get
          cors: true
    timeout: 20
  updateFaculty:
    handler: src/handler/facultys/updateFaculty.updateFaculty
    events:
      - http:
          path: facultys/{id}
          method: put
          cors: true
    timeout: 20
  deleteFaculty:
    handler: src/handler/facultys/deleteFaculty.deleteFaculty
    events:
      - http:
          path: facultys/{id}
          method: delete
          cors: true
    timeout: 20

  createSchoolYear:
    handler: src/handler/schoolYears/createSchoolYear.createSchoolYear
    events:
      - http:
          path: schoolYears
          method: post
          cors: true
  listSchoolYear:
    handler: src/handler/schoolYears/listSchoolYear.listSchoolYear
    events:
      - http:
          path: schoolYears
          method: get
          cors: true
  getSchoolYear:
    handler: src/handler/schoolYears/getSchoolYear.getSchoolYear
    events:
      - http:
          path: schoolYears/{id}
          method: get
          cors: true
  updateSchoolYear:
    handler: src/handler/schoolYears/updateSchoolYear.updateSchoolYear
    events:
      - http:
          path: schoolYears/{id}
          method: put
          cors: true
  deleteSchoolYear:
    handler: src/handler/schoolYears/deleteSchoolYear.deleteSchoolYear
    events:
      - http:
          path: schoolYears/{id}
          method: delete
          cors: true

  createForm:
    handler: src/handler/forms/createForm.createForm
    events:
      - http:
          path: forms
          method: post
          cors: true
  listForm:
    handler: src/handler/forms/listForm.listForm
    events:
      - http:
          path: forms
          method: get
          cors: true
  getForm:
    handler: src/handler/forms/getForm.getForm
    events:
      - http:
          path: forms/{id}
          method: get
          cors: true
  updateForm:
    handler: src/handler/forms/updateForm.updateForm
    events:
      - http:
          path: forms/{id}
          method: put
          cors: true
  deleteForm:
    handler: src/handler/forms/deleteForm.deleteForm
    events:
      - http:
          path: forms/{id}
          method: delete
          cors: true

  uploadFile:
    handler: src/handler/files/uploadFile.uploadFile
    events:
      - http:
          path: files
          method: post
          cors: true
    environment:
      FILE_UPLOAD_BUCKET_NAME: ${self:custom.aws_bucket_name}

  downloadFile:
    handler: src/handler/files/downloadFile.downloadFile
    events:
      - http:
          path: files/{id}
          method: get
          cors: true
  deleteFile:
    handler: src/handler/files/deleteFile.deleteFile
    events:
      - http:
          path: files/{id}
          method: delete
          cors: true